
class ParameterDynamoDBFields:
    """List of variable-SortKey fields in Parameters DynamoDB"""
    DEPLOY_IN_PROGRESS = "DEPLOY_IN_PROGRESS"
    ACCEPTED_UPDATE_VERSION = "ACCEPTED_UPDATE_VERSION"
    CANCEL_DEPLOYMENT = "CANCEL_DEPLOYMENT"
    RESTORE_IN_PROGRESS = "RESTORE_IN_PROGRESS"
    REFRESH_IN_PROGRESS = "REFRESH_IN_PROGRESS"
    BACKUP_IN_PROGRESS = "BACKUP_IN_PROGRESS"


print(type(ParameterDynamoDBFields.DEPLOY_IN_PROGRESS))


